In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[6, 9, 9, 2],
       [7, 6, 2, 8],
       [5, 1, 5, 9]])

In [5]:
arr1=np.array([1,2,3,3,4])

In [6]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [7]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [8]:
np.squeeze(arr)

array([[6, 9, 9, 2],
       [7, 6, 2, 8],
       [5, 1, 5, 9]])

In [9]:
data=np.array([[1],[2],[3]])

In [10]:
data

array([[1],
       [2],
       [3]])

In [11]:
np.squeeze(data)

array([1, 2, 3])

In [12]:
arr1

array([1, 2, 3, 3, 4])

In [13]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [16]:
np.roll(arr1,2) # shifts all the index values by 2

array([3, 4, 1, 2, 3])

In [18]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [19]:
#Numpy -binary operators

In [20]:
arr1=np.random.randint(1,10,(3,4))

In [22]:
arr2=np.random.randint(1,10,(3,4))

In [23]:
arr1+arr2

array([[12,  9, 10, 10],
       [ 9,  3, 13, 12],
       [ 8, 14,  8, 12]])

In [24]:
arr1/arr2

array([[0.33333333, 1.25      , 4.        , 0.25      ],
       [0.8       , 2.        , 2.25      , 0.5       ],
       [0.14285714, 1.33333333, 3.        , 0.33333333]])

In [25]:
arr1-arr2

array([[-6,  1,  6, -6],
       [-1,  1,  5, -4],
       [-6,  2,  4, -6]])

In [26]:
arr1%arr2

array([[3, 1, 0, 2],
       [4, 0, 1, 4],
       [1, 2, 0, 3]])

In [27]:
arr1**arr2

array([[ 19683,    625,     64,    256],
       [  1024,      2,   6561,  65536],
       [     1, 262144,     36,  19683]])

In [28]:
arr1&arr2

array([[1, 4, 0, 0],
       [4, 0, 0, 0],
       [1, 0, 2, 1]])

In [29]:
~arr1

array([[ -4,  -6,  -9,  -3],
       [ -5,  -3, -10,  -5],
       [ -2,  -9,  -7,  -4]])

In [30]:
arr1

array([[3, 5, 8, 2],
       [4, 2, 9, 4],
       [1, 8, 6, 3]])

In [31]:
arr1>arr2

array([[False,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [32]:
#Numpy - string function

In [35]:
arr=np.array(['aman','kumar'])

In [36]:
arr

array(['aman', 'kumar'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['AMAN', 'KUMAR'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Aman', 'Kumar'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Aman', 'Kumar'], dtype='<U5')

In [40]:
#Numpy - mathematical function

In [41]:
np.sin(arr1)

array([[ 0.14112001, -0.95892427,  0.98935825,  0.90929743],
       [-0.7568025 ,  0.90929743,  0.41211849, -0.7568025 ],
       [ 0.84147098,  0.98935825, -0.2794155 ,  0.14112001]])

In [42]:
np.cos(arr1)

array([[-0.9899925 ,  0.28366219, -0.14550003, -0.41614684],
       [-0.65364362, -0.41614684, -0.91113026, -0.65364362],
       [ 0.54030231, -0.14550003,  0.96017029, -0.9899925 ]])

In [43]:
np.tan(arr1)

array([[-0.14254654, -3.38051501, -6.79971146, -2.18503986],
       [ 1.15782128, -2.18503986, -0.45231566,  1.15782128],
       [ 1.55740772, -6.79971146, -0.29100619, -0.14254654]])

In [44]:
np.tanh(arr1)

array([[0.99505475, 0.9999092 , 0.99999977, 0.96402758],
       [0.9993293 , 0.96402758, 0.99999997, 0.9993293 ],
       [0.76159416, 0.99999977, 0.99998771, 0.99505475]])

In [45]:
np.log10(arr1)

array([[0.47712125, 0.69897   , 0.90308999, 0.30103   ],
       [0.60205999, 0.30103   , 0.95424251, 0.60205999],
       [0.        , 0.90308999, 0.77815125, 0.47712125]])

In [46]:
np.exp(arr1)

array([[2.00855369e+01, 1.48413159e+02, 2.98095799e+03, 7.38905610e+00],
       [5.45981500e+01, 7.38905610e+00, 8.10308393e+03, 5.45981500e+01],
       [2.71828183e+00, 2.98095799e+03, 4.03428793e+02, 2.00855369e+01]])

In [47]:
np.sqrt(arr1)

array([[1.73205081, 2.23606798, 2.82842712, 1.41421356],
       [2.        , 1.41421356, 3.        , 2.        ],
       [1.        , 2.82842712, 2.44948974, 1.73205081]])

In [48]:
np.power(arr1,2)

array([[ 9, 25, 64,  4],
       [16,  4, 81, 16],
       [ 1, 64, 36,  9]])

In [49]:
np.mean(arr1)

4.583333333333333

In [50]:
np.median(arr1)

4.0

In [52]:
np.std(arr1)

2.5317429218272185

In [53]:
np.max(arr1)

9

In [54]:
np.min(arr1)

1

In [55]:
#sort,search and counting function

In [56]:
import numpy as np

In [61]:
arr=np.random.randint(1,100,10)

In [62]:
arr

array([77, 10, 63, 28, 64, 61,  2, 22, 58, 93])

In [63]:
np.sort(arr)

array([ 2, 10, 22, 28, 58, 61, 63, 64, 77, 93])

In [64]:
np.searchsorted(arr,2)

0

In [65]:
arr1=np.array([0,345,454,0,0,0,0,0])

In [66]:
np.count_nonzero(arr1)

2

In [67]:
arr

array([77, 10, 63, 28, 64, 61,  2, 22, 58, 93])

In [68]:
np.where(arr>6)

(array([0, 1, 2, 3, 4, 5, 7, 8, 9]),)

In [69]:
np.extract(arr>3,arr)

array([77, 10, 63, 28, 64, 61, 22, 58, 93])

In [70]:
#Numpy -byte swapping

In [71]:
arr

array([77, 10, 63, 28, 64, 61,  2, 22, 58, 93])

In [74]:
arr.byteswap() # shows the byte respresentation

array([5548434740920451072,  720575940379279360, 4539628424389459968,
       2017612633061982208, 4611686018427387904, 4395513236313604096,
        144115188075855872, 1585267068834414592, 4179340454199820288,
       6701356245527298048])

In [75]:
# Numpy - copies and views

In [80]:
a=np.copy(arr) # deep copy

In [81]:
b=arr.view() # swallow copy 

In [82]:
b

array([77, 10, 63, 28, 64, 61,  2, 22, 58, 93])

In [83]:
a

array([77, 10, 63, 28, 64, 61,  2, 22, 58, 93])

In [84]:
# Numpy - matrix library

In [85]:
import numpy.matlib as nm

In [86]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [87]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [89]:
# numpy - linear algebra

In [90]:
arr1=np.random.randint([[2,3],[4,5]])

In [91]:
arr1

array([[0, 0],
       [2, 2]])

In [92]:
arr2=np.random.randint([[5,3],[2,5]])

In [93]:
arr2

array([[2, 1],
       [1, 3]])

In [94]:
np.dot(arr1,arr2)

array([[0, 0],
       [6, 8]])

In [95]:
arr1@arr2

array([[0, 0],
       [6, 8]])