In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]
ar=np.array(l)

In [3]:
type(ar)

numpy.ndarray

In [4]:
# nd mean n dimensional array

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
a=[2,3,4]

In [8]:
np.asanyarray(a)

array([2, 3, 4])

In [9]:
b=np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
np.asanyarray(b) # this will not convert the matrix in the array as 
# the matrix is also a type of array only, basically subset of array only 

matrix([[1, 2, 3, 4]])

In [12]:
a=np.array(l)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
c=a # swallow copy

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0]=100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a  # this also changes because a and c both are pointing to the same memory

array([100,   2,   3,   4])

In [21]:
d=np.copy(a) #this makes the deep copy and now if we will change anything in the 
# a then it will not affect the d 

In [22]:
a[1]=400

In [23]:
a

array([100, 400,   3,   4])

In [24]:
d

array([100,   2,   3,   4])

In [25]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable=(i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('123 12',sep=" ")

array([123.,  12.])

In [32]:
np.fromstring('4,5',sep=",")

array([4., 5.])

In [33]:
#Numpy - Data Types
l=[2,3,4,5,6]

In [34]:
ar=np.array(l)

In [35]:
ar

array([2, 3, 4, 5, 6])

In [36]:
ar.ndim

1

In [37]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [38]:
ar2.ndim

2

In [39]:
ar.size

5

In [40]:
ar2.size

8

In [41]:
ar.shape

(5,)

In [42]:
ar2.shape

(2, 4)

In [44]:
ar.dtype

dtype('int64')

In [45]:
ar2.dtype

dtype('int64')

In [46]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [47]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [48]:
ar22.dtype

dtype('float64')

In [49]:
range(5)

range(0, 5)

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [52]:
np.arange(2.3,5.6,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [53]:
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [55]:
np.linspace(1,5,10) # produces 10 entries with equal interval

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros((3,4,2)) # we have 3 matrx with 4x2 matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
on=np.ones((2,3,2))

In [64]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [65]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [66]:
np.empty((3,5))

array([[4.66163695e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [72]:
np.logspace(2,4,20,base=2)

array([ 4.        ,  4.30276234,  4.62844095,  4.97877036,  5.3556164 ,
        5.76098615,  6.19703857,  6.66609605,  7.17065677,  7.71340798,
        8.29724036,  8.92526334,  9.60082176, 10.32751358, 11.10920914,
       11.95007169, 12.85457963, 13.82755029, 14.87416568, 16.        ])

In [73]:
np.logspace(2,4,20) # default base 10

array([  100.        ,   127.42749857,   162.37767392,   206.91380811,
         263.66508987,   335.98182863,   428.13323987,   545.55947812,
         695.19279618,   885.86679041,  1128.83789168,  1438.44988829,
        1832.98071083,  2335.72146909,  2976.35144163,  3792.69019073,
        4832.93023857,  6158.48211066,  7847.59970351, 10000.        ])

In [81]:
arr=np.random.randn(3,4) # this generates a data from standard normal distribution 
# which means that the mean of data produced will be 0 and std will be 1

In [82]:
arr

array([[-1.23115422,  1.08572993, -0.03641631, -0.43257177],
       [-0.20522682, -1.75625021,  0.95670788,  0.24753613],
       [ 0.23151506,  0.14656041, -1.23007414,  2.21214202]])

In [83]:
import pandas as pd

In [84]:
pd.DataFrame(arr)

0        1         2         3
0 -1.231154  1.08573 -0.036416 -0.432572
1 -0.205227 -1.75625  0.956708  0.247536
2  0.231515  0.14656 -1.230074  2.212142

In [85]:
np.random.rand(3,4)

array([[0.63757536, 0.56027986, 0.44350119, 0.98148097],
       [0.13934853, 0.65801683, 0.61816594, 0.67066117],
       [0.50161693, 0.37720178, 0.52702344, 0.53234839]])

In [86]:
np.random.randint(1,110,(3,4))

array([[ 99,  26,  75,  24],
       [ 98,  99,  38,  16],
       [ 23,  94, 108,  71]])

In [87]:
arr

array([[-1.23115422,  1.08572993, -0.03641631, -0.43257177],
       [-0.20522682, -1.75625021,  0.95670788,  0.24753613],
       [ 0.23151506,  0.14656041, -1.23007414,  2.21214202]])

In [88]:
arr.shape

(3, 4)

In [89]:
arr.reshape(2,6)

array([[-1.23115422,  1.08572993, -0.03641631, -0.43257177, -0.20522682,
        -1.75625021],
       [ 0.95670788,  0.24753613,  0.23151506,  0.14656041, -1.23007414,
         2.21214202]])

In [90]:
arr.reshape(6,-1)

array([[-1.23115422,  1.08572993],
       [-0.03641631, -0.43257177],
       [-0.20522682, -1.75625021],
       [ 0.95670788,  0.24753613],
       [ 0.23151506,  0.14656041],
       [-1.23007414,  2.21214202]])

In [94]:
arr.reshape(-154949,4)

array([[-1.23115422,  1.08572993, -0.03641631, -0.43257177],
       [-0.20522682, -1.75625021,  0.95670788,  0.24753613],
       [ 0.23151506,  0.14656041, -1.23007414,  2.21214202]])

In [95]:
arr[1]

array([-0.20522682, -1.75625021,  0.95670788,  0.24753613])

In [96]:
arr[1][1]

-1.756250209123155

In [99]:
arr[1:,1:3]

array([[-1.75625021,  0.95670788],
       [ 0.14656041, -1.23007414]])

In [100]:
arr=np.random.randint(1,100,(5,5))

In [101]:
arr

array([[21, 99, 55, 52, 31],
       [15, 88, 36, 46, 15],
       [70, 58, 22, 71, 69],
       [80, 42,  5, 53, 33],
       [34, 36, 88, 71, 79]])

In [103]:
arr[arr>50]

array([99, 55, 52, 88, 70, 58, 71, 69, 80, 53, 88, 71, 79])

In [104]:
arr>50

array([[False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True,  True, False,  True,  True],
       [ True, False, False,  True, False],
       [False, False,  True,  True,  True]])

In [105]:
arr[0][0]=5000

In [106]:
arr

array([[5000,   99,   55,   52,   31],
       [  15,   88,   36,   46,   15],
       [  70,   58,   22,   71,   69],
       [  80,   42,    5,   53,   33],
       [  34,   36,   88,   71,   79]])

In [110]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [111]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [112]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [113]:
arr1+arr2

array([[3, 4, 4],
       [2, 2, 3],
       [4, 4, 2]])

In [114]:
arr1*arr2

array([[2, 4, 4],
       [1, 1, 2],
       [4, 4, 1]])

In [116]:
arr1@arr2 #matrix multiplication

array([[8, 8, 6],
       [7, 7, 5],
       [8, 8, 7]])

In [118]:
arr1/0

/tmp/ipykernel_1620/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [119]:
arr2**2

array([[4, 4, 4],
       [1, 1, 1],
       [4, 4, 1]])

In [120]:
#numpy - broadcasting

In [121]:
arr=np.zeros((4,4))

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
row=np.array([1,2,3,4])

In [126]:
arr+row # row wise broading

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
col=np.array([[1,2,3,4]])

In [128]:
col.T+arr # column wise broading casting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [129]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [130]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ]])

In [131]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [132]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ]])

In [133]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [135]:
arr1.flatten()

array([1, 2, 2, 1, 1, 2, 2, 2, 1])

In [136]:
arr1=np.array([1,2,3,3,4])